create table member
(
    id                 bigint generated by default as identity,
    nickname           varchar(10) not null,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    primary key (id)
);

create table participant_code
(
    id                 bigint generated by default as identity,
    code               varchar(6) unique,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    primary key (id)
);

create table pomodoro_content
(
    id                   bigint generated by default as identity,
    pomodoro_progress_id bigint,
    cycle                integer not null,
    plan                 text,
    retrospect           text,
    created_date         timestamp(6),
    last_modified_date   timestamp(6),
    primary key (id)
);

create table pomodoro_progress
(
    id                 bigint generated by default as identity,
    pomodoro_room_id   bigint,
    member_id          bigint,
    is_done            boolean not null,
    current_cycle      integer not null,
    pomodoro_status    varchar(255) check (pomodoro_status in ('PLANNING', 'STUDYING', 'RETROSPECT')),
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    primary key (id)
);

create table pomodoro_room
(
    id                  bigint generated by default as identity,
    participant_code_id bigint unique,
    name                varchar(10) not null,
    total_cycle         integer     not null,
    time_per_cycle      integer     not null,
    created_date        timestamp(6),
    last_modified_date  timestamp(6),
    primary key (id)
);
