spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
    open-in-view: false

  flyway:
    enabled: false

  config:
    import:
      - classpath:/submodule/application-auth-production.yml
      - classpath:/submodule/application-db-production.yml

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: prometheus, logfile
  endpoint:
    prometheus:
      enabled: true
    logfile:
      external-file: ./logs/default/default.log
