spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true

  config:
    import:
      - classpath:/submodule/application-auth.yml
      - classpath:/submodule/application-db-develop.yml

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: prometheus, logfile
  endpoint:
    prometheus:
      enabled: true
    logfile:
      external-file: ./logs/default/default.log
