spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  flyway:
    enabled: false

    placeholders:
      dialect: h2

  config:
    import: classpath:/submodule/application-auth-develop.yml
