spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
    show-sql: true
    open-in-view: false

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  flyway:
    enabled: false

  config:
    import: classpath:/submodule/application-auth-develop.yml
