# workflow의 이름
name: backend-build-test

# PR 요청에 대해
on:
  pull_request:
    branches:
      - develop
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

# 실행 해야할 job
jobs:
  check-label-id:
    runs-on: ubuntu-latest
    # 각 단계
    steps:
      # 소스코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v3
      # 빌드
      - name: label Test
        run: cat $GITHUB_EVENT_PATH