name: backend-build-test

on:
  pull_request:
    branches:
      - develop
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./backend

jobs:
  build-test:
    # label이 (BE && feature) || (BE && refactor)일 경우 실행
    if: |
      (contains(github.event.pull_request.labels.*.id, 5686155001) &&
      contains(github.event.pull_request.labels.*.id, 5681142648)) ||
      (contains(github.event.pull_request.labels.*.id, 5686155001) &&
      contains(github.event.pull_request.labels.*.id, 5681143873))

    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Test
        run: ./gradlew build

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Github Action # default: 8398a7@action-slack
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always()
